#!/bin/sh

base=`dirname $0`

for dir in "$@"; do
  if [ ! -d "$dir" ]; then
    continue
  fi
  echo "create-source-packages in $dir"
  (
    cd "$dir" &&
    git clean -xfd
    git submodule status --recursive | while read a d r; do (cd $d && git clean -xfd); done
    git checkout .
    git checkout master
    git branch -D release
    git fetch --all -pt &&
    git checkout -b release `git tag | tail -n 1` &&
    git submodule update --init &&
    "../$base/create-source-packages" all
  ) || echo "FAILED"
done
