#!/bin/sh

echo "Signing dummy file"
rm -f /tmp/dummy.$$*
touch /tmp/dummy.$$
gpg --sign /tmp/dummy.$$

for what in squeeze; do
	sed -i 's%~unstable%~squeeze%g' debian/changelog debian/control
	dpkg-buildpackage -i -I
	rm debian/changelog debian/control
	git checkout debian/changelog debian/control
done

