#!/bin/sh

echo "Signing dummy file"
rm -f /tmp/dummy.$$* &&
touch /tmp/dummy.$$ &&
gpg --sign /tmp/dummy.$$ &&
rm debian/changelog debian/control &&
git checkout debian/changelog debian/control &&
if [ -f Makefile.PL ]; then
  rm -f Makefile
fi &&

for what in squeeze; do
	sed -i "s%~unstable%~$what%g" debian/changelog debian/control &&
	dpkg-buildpackage -i -I &&
	rm debian/changelog debian/control &&
	git checkout debian/changelog debian/control || break
done

