#!/bin/sh -e

if [ ! -d epel ]; then
	echo "no epel directory, exit"
	exit 1
fi

sign="--sign"
basename=`basename $PWD`
specfile=`(cd epel && ls -1 *.spec | head -n 1)`

if [ ! -f "epel/$specfile" ]; then
	echo "no specfile found, exit"
	exit 1
fi

if [ "$nosign" != "" ]; then
  sign=""
fi

version=`grep '^Version:' epel/$specfile | head -n 1 | awk '{print $2}'`

if [ -d epel/patches ]; then
	cp -v epel/patches/*.patch ~/rpmbuild/SOURCES/ 2>/dev/null
fi

cp -v epel/$specfile ~/rpmbuild/SPECS/
( cd .. && tar --exclude-vcs -zcvf ~/rpmbuild/SOURCES/$basename-$version.tar.gz $basename )
rpmbuild -ba $sign -v ~/rpmbuild/SPECS/$specfile

echo "ok"
