#!/bin/sh

if [ -z "$1" -o -z "$2" ]; then
	echo "usage: $0 <epel base directory> <rpm names...>"
	exit 1
fi

epel_base_dir="$1"
shift
for name in $@; do
	echo "$name"
	cp -v ~/rpmbuild/SRPMS/$name*.src.rpm $epel_base_dir/SRPMS || exit
	for arch in noarch; do
		cp -v ~/rpmbuild/RPMS/noarch/$name*.rpm $epel_base_dir/$arch || exit
	done
done
echo OK
