#!/bin/sh -e

spec=
if [ -d rpm ]; then
	spec=`(cd rpm && ls -1 *.spec 2>/dev/null | head -n 1)`
fi

if [ ! -f "rpm/$spec" ]; then
	echo "Not in the right directory, cant find RPM spec"
	exit 1
fi

name_vers=`grep -A 1 %changelog "rpm/$spec" | tail -n 1 | cut -d ' ' -f 6-`
date=`LC_ALL=en_US.UTF-8 date "+%a %b %d %Y"`

sed -i -e "s/%changelog/%changelog\n* $date $name_vers\n- change/" "rpm/$spec"

echo "ok"
