#!/bin/sh -e

spec=
if [ -d rpm ]; then
	spec=`(cd rpm && ls -1 *.spec 2>/dev/null | head -n 1)`
fi

if [ ! -f "rpm/$spec" ]; then
	echo "Not in the right directory, cant find RPM spec"
	exit 1
fi

name_vers=`grep -A 1 %changelog "rpm/$spec" | tail -n 1 | cut -d ' ' -f 6-`
date=`LC_ALL=en_US.UTF-8 date "+%a %b %d %Y"`

if [ -z "$message" ]; then
  message="change me"
fi

if [ -n "$auto_build_number" ]; then
  name_vers=`echo "$name_vers" | sed "s%\(-[0-9]\)%.$auto_build_number\1%"`
  sed -i -e "s/\(^Version:.*\)/\1.$auto_build_number/" "rpm/$spec"
fi

sed -i -e "s/%changelog/%changelog\n* $date $name_vers\n- $message/" "rpm/$spec"

echo "ok"
