#!/bin/sh

release=`lsb_release -c | awk '{print $2}'`
if [ -z "$release" ]; then
        echo "could not get release codename, exit"
        exit 1
fi

echo "Signing dummy file"
rm -f /tmp/dummy.$$* &&
touch /tmp/dummy.$$ &&
gpg --sign /tmp/dummy.$$ &&
rm debian/changelog debian/control &&
git checkout debian/changelog debian/control &&
if [ -f Makefile.PL ]; then
  rm -f Makefile
fi &&

for what in lucid maverick natty oneiric precise; do
	sed -i "s%~unstable%~$what%g" debian/changelog debian/control &&
	sed -i "s%) unstable;%) $what;%g" debian/changelog &&
	if [ "$what" = "$release" ]; then
		dpkg-buildpackage -i -I
	fi &&
	dpkg-buildpackage -i -I -S &&
	rm debian/changelog debian/control &&
	git checkout debian/changelog debian/control || break
done

