#!/bin/sh

for what in lucid maverick natty oneiric precise; do
	if git branch | grep -q $what; then
		git checkout $what &&
		git pull
	else
		git checkout -b $what origin/$what
	fi || break
done &&
git checkout master

