#!/bin/sh -e

if [ -z "$1" ]; then
	echo "usage: $0 <ppa name>"
	exit 1
fi

ppa="$1"
shift

if ! echo "$ppa" | grep -q '^ppa:'; then
    ppa="ppa:jelu/$ppa"
fi

for what in $@; do
	dput "$ppa" $what
done

echo "ok"
