#!/bin/sh -e

base=`dirname $0`
image=`( cd "$base" && cat NAME )`
update=`echo "$image" | sed 's%:%-%g'`

docker run \
  -t \
  --name "$update" \
  "$image" \
  bash -c 'yum -y update'

docker commit "$update" "$image"

docker rm "$update"
